/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.EliminarControlador;
import javax.swing.ButtonGroup;
import modelo.Producto;
import modelo.Venta;

/**
 *
 * @author USUARIO
 */
public class EliminarVista extends javax.swing.JFrame {

    /**
     * Creates new form EliminarVista
     */
    public EliminarVista() {
        initComponents();
        
       buttonGroup1.add(this.elimdet);
        buttonGroup1.add(this.elimprod);
       buttonGroup1.add(this.elimvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idprod = new javax.swing.JTextField();
        elimprod = new javax.swing.JRadioButton();
        elimvent = new javax.swing.JRadioButton();
        elimdet = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        idventa = new javax.swing.JTextField();
        botoneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eliminar Registro");

        jLabel2.setText("Id Producto");

        elimprod.setText("Eliminar Producto");
        elimprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimprodActionPerformed(evt);
            }
        });

        elimvent.setText("Eliminar Venta");
        elimvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimventActionPerformed(evt);
            }
        });

        elimdet.setText("Eliminar Detalle Venta");
        elimdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimdetActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Venta");

        idventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idventaActionPerformed(evt);
            }
        });

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(elimprod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elimvent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elimdet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idventa, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(idprod)))
                    .addComponent(botoneliminar))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elimprod)
                    .addComponent(elimvent)
                    .addComponent(elimdet))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(botoneliminar)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elimventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimventActionPerformed
        this.idprod.setEnabled(false);
 this.idventa.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_elimventActionPerformed

    private void idventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idventaActionPerformed

    private void elimprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimprodActionPerformed
      this.idventa.setEnabled(false);
      this.idprod.setEnabled(true); 
      
    }//GEN-LAST:event_elimprodActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
         
        EliminarControlador elim = new EliminarControlador ();
        Producto producto = new Producto ();
        Venta venta = new Venta ();
        if(this.elimprod.isSelected()){
            producto.setId_producto(Integer.parseInt(this.idprod.getText()));
            System.out.println(producto.getId_producto());
            elim.eliminardet1(producto);
           elim.eliminarprod(producto);
        
        }else if(this.elimvent.isSelected()){
        venta.setIdventa(Integer.parseInt(this.idventa.getText()));
        elim.eliminardet2(venta);
        elim.eliminarvemta(venta);
      
        }else if (this.elimdet.isSelected()){
        
        producto.setId_producto(Integer.parseInt(this.idprod.getText()));
        venta.setIdventa(Integer.parseInt(this.idventa.getText()));
        elim.eliminardet3(venta, producto);
        
        }
            

        // TODO add your handling code here:
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void elimdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimdetActionPerformed
        this.idventa.setEnabled(true);
        this.idprod.setEnabled(true);   
    }//GEN-LAST:event_elimdetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton elimdet;
    private javax.swing.JRadioButton elimprod;
    private javax.swing.JRadioButton elimvent;
    private javax.swing.JTextField idprod;
    private javax.swing.JTextField idventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
